import React,{useState}from"react";import{createRoot}from"react-dom/client";import{ArrowRight,CheckCircle2,Code2,Database,Menu,MessageCircle,MonitorCog,ShieldCheck,X}from"lucide-react";import"./style.css";
const systems=[
["TiendaApp","Comercios","tiendaapp.png","Sistema de gestión para comercios, ventas, productos y control de stock.",["Ventas","Stock","Productos","Reportes"]],
["GrumPet","Veterinarias","grumpet.png","Sistema de gestión para pet shops y negocios dedicados a productos para mascotas.",["Productos","Ventas","Stock","Clientes"]],
["GrumDent","Salud","grumdent.png","Sistema de gestión para consultorios y profesionales de odontología.",["Pacientes","Consultas","Historia clínica","Gestión"]],
["Talvena","Salud","talvena.png","Sistema de gestión clínica para organizar pacientes, médicos y consultas.",["Pacientes","Médicos","Signos","Historia médica"]],
["TallerPro","Servicios","tallerpro.png","Sistema de gestión para talleres mecánicos y seguimiento de reparaciones.",["Clientes","Vehículos","Órdenes","Historial"]],
["VerdaMax","Comercios","verdadmax.png","Solución orientada a la gestión de comercios de frutas y verduras.",["Productos","Ventas","Stock","Gestión"]]];
const cats=["Todos","Comercios","Salud","Veterinarias","Servicios"];
function App(){const[c,setC]=useState("Todos"),[m,setM]=useState(false),[sel,setSel]=useState(null);const wa="https://wa.me/3804881636?text=Hola%20GRUMEP,%20quiero%20consultar%20por%20un%20sistema.";const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setM(false)};const list=c==="Todos"?systems:systems.filter(x=>x[1]===c);return <><header><div className="container nav"><button className="brand"onClick={()=>go("inicio")}><b>G</b><span><strong>GRUMEP</strong><small>Consultora de Desarrollo de Software</small></span></button><nav className={m?"open":""}><button onClick={()=>go("inicio")}>Inicio</button><button onClick={()=>go("desarrollos")}>Desarrollos</button><button onClick={()=>go("servicios")}>Servicios</button><button onClick={()=>go("nosotros")}>Nosotros</button><button className="cta"onClick={()=>go("contacto")}>Contacto</button></nav><button className="menu"onClick={()=>setM(!m)}>{m?<X/>:<Menu/>}</button></div></header>
<section id="inicio"className="hero"><div className="container heroGrid"><div><label>SOFTWARE QUE SE ADAPTA A TU NEGOCIO</label><h1>Soluciones digitales para <em>hacer crecer</em> tu negocio.</h1><p>Desarrollamos sistemas de gestión modernos, prácticos y adaptados a las necesidades reales de comercios, profesionales y empresas.</p><div className="actions"><button className="primary"onClick={()=>go("desarrollos")}>Ver nuestros desarrollos <ArrowRight/></button><a className="secondary"href={wa}target="_blank"><MessageCircle/> Solicitar demostración</a></div><div className="trust"><span><CheckCircle2/> Desarrollo personalizado</span><span><CheckCircle2/> Soporte</span><span><CheckCircle2/> Soluciones escalables</span></div></div><div className="mock"><div>GRUMEP / SOFTWARE</div><main><aside><b>G</b><i/><i/><i/><i/></aside><article><small>PANEL DE GESTIÓN</small><h3>Tu negocio, bajo control.</h3><section><span>Ventas<strong>$ 1.250.000</strong></span><span>Productos<strong>1.284</strong></span><span>Clientes<strong>428</strong></span></section><div className="chart"><i/><i/><i/><i/><i/><i/></div></article></main></div></div></section>
<section className="stats"><div className="container"><span><b>6+</b>Desarrollos presentados</span><span><b>100%</b>Adaptables</span><span><b>4</b>Rubros</span><span><b>1</b>Objetivo: hacer crecer tu negocio</span></div></section>
<section id="desarrollos"className="section"><div className="container"><div className="heading"><div><label>PORTAFOLIO</label><h2>Nuestros <em>desarrollos</em></h2></div><p>Conocé los sistemas que estamos desarrollando para distintos tipos de negocios y profesionales.</p></div><div className="filters">{cats.map(x=><button className={c===x?"active":""}onClick={()=>setC(x)}key={x}>{x}</button>)}</div><div className="grid">{list.map(s=><article className="card"key={s[0]}><div className="image"><img src={"/images/"+s[2]}alt={s[0]}/><span>{s[1]}</span></div><div className="body"><h3>{s[0]}</h3><p>{s[3]}</p><div className="features">{s[4].map(f=><small key={f}>{f}</small>)}</div><button onClick={()=>setSel(s)}>Ver detalles <ArrowRight/></button></div></article>)}</div></div></section>
<section id="servicios"className="section dark"><div className="container"><div className="heading light"><div><label>SERVICIOS</label><h2>Software para cada <em>necesidad</em></h2></div><p>No necesitás adaptar tu negocio a un sistema. Adaptamos el sistema a tu negocio.</p></div><div className="services">{[[MonitorCog,"Sistemas de gestión","Ventas, clientes, stock, turnos y operaciones."],[Code2,"Desarrollo a medida","Software creado según los procesos de tu empresa."],[Database,"Bases de datos","Organización y gestión de la información."],[ShieldCheck,"Soporte y evolución","Mantenimiento, mejoras y nuevas funcionalidades."]].map(([I,t,d])=><div className="service"key={t}><I/><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
<section id="nosotros"className="section about"><div className="container aboutGrid"><div className="aboutLogo">G</div><div><label>SOBRE GRUMEP</label><h2>Transformamos ideas en <em>software.</em></h2><p>GRUMEP es una consultora enfocada en el desarrollo de soluciones de software para negocios y profesionales.</p><p>Buscamos crear herramientas simples de usar, útiles para el día a día y preparadas para acompañar el crecimiento de cada cliente.</p><div className="points"><span><CheckCircle2/> Tecnología aplicada a problemas reales</span><span><CheckCircle2/> Sistemas fáciles de usar</span><span><CheckCircle2/> Desarrollo pensado para crecer</span></div></div></div></section>
<section id="contacto"className="contact"><div className="container contactBox"><div><label>¿TENÉS UN PROYECTO?</label><h2>Hablemos sobre <em>tu idea.</em></h2><p>Contanos qué necesitás y evaluamos juntos la mejor solución para tu negocio.</p></div><a className="primary"href={wa}target="_blank"><MessageCircle/> Contactar por WhatsApp</a></div></section>
<footer><div className="container footer"><div><div className="fbrand"><b>G</b><strong>GRUMEP</strong></div><p>Consultora de Desarrollo de Software.</p></div><div><h4>Navegación</h4><button onClick={()=>go("desarrollos")}>Desarrollos</button><button onClick={()=>go("servicios")}>Servicios</button><button onClick={()=>go("contacto")}>Contacto</button></div><div><h4>Contacto</h4><a href={wa}target="_blank">WhatsApp</a><span>La Rioja, Argentina</span></div></div><div className="copy">© 2026 GRUMEP. Todos los derechos reservados.</div></footer>
{sel&&<div className="modalBg"onClick={()=>setSel(null)}><div className="modal"onClick={e=>e.stopPropagation()}><button className="close"onClick={()=>setSel(null)}><X/></button><img src={"/images/"+sel[2]}alt={sel[0]}/><label>{sel[1]}</label><h2>{sel[0]}</h2><p>{sel[3]}</p><h4>Funcionalidades</h4><div className="modalFeatures">{sel[4].map(f=><span key={f}><CheckCircle2/>{f}</span>)}</div><a className="primary"href={wa}target="_blank"><MessageCircle/> Solicitar demostración</a></div></div>}</>}
createRoot(document.getElementById("root")).render(<App/>);